apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sampleApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleApp
  template:
    metadata:
      labels:
        app: sampleApp
    spec:
      containers:
      - name: sampleContainer
        image: nginx:1.7.9
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
  ---
  apiVersion: v1
kind: Service
metadata:
  name: sampleApp-service
  labels:
    app: sampleApp
spec:
  type: NodePort
  selector:
    app: sampleApp
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
